[package]
name = "ar5iv"
version = "0.2.2"
edition = "2021"
default-run = "ar5iv"

[dependencies]
lazy_static = "1.4.0"
regex = "1.5.4"
zip = "0.5"
walkdir = "2"
redis = "0.21.2"
rand = "0.8.4"
crossbeam = "0.8.1"
libxml = "0.3.0"
unicode-segmentation = "1.8.0"

[[bin]]
path = "src/main.rs"
name = "ar5iv"

[[bin]]
path = "bin/cache_adjacency_map.rs"
name = "cache_adjacency_map"

[dev-dependencies]
criterion = {version = "0.3.5", features=["async_tokio"]}

[[bench]]
name = "dirty_render"
harness = false

[dependencies.rocket]
git="https://github.com/SergioBenitez/Rocket"
version="0.5.0-rc.2"

[dependencies.rocket_dyn_templates]
git="https://github.com/SergioBenitez/Rocket"
version = "0.1.0-rc.2"
features = ["tera"]

[dependencies.rocket_db_pools]
git="https://github.com/SergioBenitez/Rocket"
version = "0.1.0-rc"
features = ["deadpool_redis"]